@startuml ResolveCollision

participant "Collision Resolver" as Resolver
participant "World Repository" as Repository
participant "Collision Detector" as Detector
participant "Collision Handler" as Handler

Resolver -> Repository: Retrieve list of world bodies
Repository --> Resolver: List of particles
loop for each collision
    Resolver -> Detector: Detect collisions between two particles
    Detector -> Handler: Update particle positions and velocities
    Handler --> Detector
    Detector --> Resolver
end repeat
