@startuml ResolveMotion

participant "Motion Resolver" as Updater
participant "World Repository" as Repository
participant "Verlet Motion Equation" as Verlet

Updater -> Repository: Retrieve list of world bodies
Repository --> Updater: List of particles
loop for each particle
    Updater -> Verlet: Apply verlet motion equation to particle
    Verlet --> Updater: Updated particle position
end repeat
Updater -> Repository: Update particle positions
Repository --> Updater

@enduml
