@startuml UseCases

actor User
usecase "Create particle" as UC_CreateParticle
usecase "Destroy particle" as UC_DestroyParticle
usecase "Step Simulation" as UC_Step
usecase "Update Positions" as UC_Motion
usecase "Resolve Collision" as UC_Collision
entity "Particle" as E_Particle
entity "Motion" as E_Motion
entity "Collision Detection" as E_Detection
entity "Collision Resolution" as E_Resolution

User --> UC_CreateParticle
User --> UC_DestroyParticle
User --> UC_Step

UC_CreateParticle --> E_Particle
UC_DestroyParticle --> E_Particle

UC_Step --> UC_Motion
UC_Step --> UC_Collision

UC_Motion --> E_Motion
UC_Motion --> E_Particle

UC_Collision --> E_Detection
UC_Collision --> E_Resolution
UC_Collision --> E_Particle

E_Detection --> E_Particle

E_Resolution --> E_Particle

@enduml
